### PR TITLE
Remove postgis-vt-util

### PR DESCRIPTION
**Pull request by ghost**
Needs quick test.

### CODE REVIEW

**Comment by jirik** [comment]
@stirringhalo Why do you want to remove it? I am just curious.
If I can help you with the test, let me know how.

**Comment by jirik** [comment]
Aha, because you moved it to [openmaptiles/postgis](https://github.com/openmaptiles/postgis/commit/b06a5ce4006f2a830c368929ed5a161e60414caa), right?

**Comment by ghost** [comment]
Yep, I won't do it yet as I'm still working on getting a good Zres build.

**Comment by ghost** [comment]
I will close this, unnecessary with new approach. I am tempted to revert postgis to prior to addition of postgis-vt-util as the change isn't necessary.

**Pull request closed without merging**
